#!/usr/bin/env python3
"""SCAMPER Generator - Generate SCAMPER ideation prompts for product features.

Takes a feature or product description and generates structured prompts
across all 7 SCAMPER dimensions to stimulate creative thinking.

Usage:
    python scamper_generator.py --feature "User onboarding flow"
    python scamper_generator.py --feature "User onboarding flow" --json
    python scamper_generator.py --input input.json
"""

import argparse
import json
import sys


SCAMPER_DIMENSIONS = {
    "Substitute": {
        "description": "What components, materials, or processes can be replaced?",
        "prompts": [
            "What if we replaced {feature} with a completely different approach?",
            "What technology could substitute for the current implementation?",
            "What if a different user action triggered this instead?",
            "Could we substitute the manual step with automation?",
            "What if we replaced the UI with a conversational interface?",
        ],
    },
    "Combine": {
        "description": "What features, ideas, or processes can be merged?",
        "prompts": [
            "What if {feature} was combined with another feature users commonly use together?",
            "Could we merge this step with the previous or next step?",
            "What if we bundled this with the user's most common next action?",
            "Could two separate screens become one unified experience?",
            "What data from another part of the product could enhance this?",
        ],
    },
    "Adapt": {
        "description": "What can be borrowed from other products or contexts?",
        "prompts": [
            "What would {feature} look like if designed by a gaming company?",
            "How do social media apps solve a similar problem?",
            "What pattern from e-commerce could we adapt here?",
            "How would this work if adapted for a mobile-first context?",
            "What approach do our top competitors use that we could improve upon?",
        ],
    },
    "Modify": {
        "description": "What can be magnified, minimized, or changed in form?",
        "prompts": [
            "What if {feature} was 10x simpler with fewer options?",
            "What if we made the output 10x more detailed/comprehensive?",
            "What would change if we served power users instead of beginners?",
            "How would this change if the time constraint was halved?",
            "What if we changed the frequency (daily -> real-time, or weekly -> on-demand)?",
        ],
    },
    "Put to other use": {
        "description": "Can this feature serve a different purpose or audience?",
        "prompts": [
            "Who else (beyond the current users) would benefit from {feature}?",
            "Could this feature serve an internal team's need as well?",
            "What if we exposed this as an API for third-party developers?",
            "Could the data generated by this feature power a different insight?",
            "What if this became a standalone product instead of a feature?",
        ],
    },
    "Eliminate": {
        "description": "What can be removed, simplified, or made unnecessary?",
        "prompts": [
            "What if we removed {feature} entirely -- what would users do instead?",
            "Which step in the current flow adds the least value?",
            "What if we eliminated all optional fields and kept only required ones?",
            "Could we remove a decision point by making it automatic?",
            "What would happen if we eliminated the confirmation step?",
        ],
    },
    "Reverse": {
        "description": "What if we reversed the order, roles, or direction?",
        "prompts": [
            "What if the user received the output of {feature} first, then provided input?",
            "What if the system did the work and the user only reviewed/approved?",
            "What if we reversed the sequence of steps?",
            "What if instead of the user finding content, the content found the user?",
            "What if we started from the end goal and worked backward?",
        ],
    },
}


def generate_scamper(feature: str) -> dict:
    """Generate SCAMPER prompts for a feature."""
    dimensions = []
    for name, dim in SCAMPER_DIMENSIONS.items():
        prompts = [p.replace("{feature}", feature) for p in dim["prompts"]]
        dimensions.append({
            "dimension": name,
            "description": dim["description"],
            "prompts": prompts,
        })

    return {
        "feature": feature,
        "total_prompts": sum(len(d["prompts"]) for d in dimensions),
        "dimensions": dimensions,
        "instructions": "For each prompt, generate 1-2 concrete ideas. Then select the top 3-5 ideas across all dimensions for further evaluation.",
    }


def print_report(result: dict) -> None:
    print(f"\nSCAMPER Ideation: {result['feature']}")
    print("=" * 60)
    print(f"Total Prompts: {result['total_prompts']}")
    print(f"\n{result['instructions']}")

    for dim in result["dimensions"]:
        print(f"\n--- {dim['dimension'].upper()} ---")
        print(f"    {dim['description']}")
        for i, prompt in enumerate(dim["prompts"], 1):
            print(f"    {i}. {prompt}")
    print()


def main():
    parser = argparse.ArgumentParser(description="Generate SCAMPER ideation prompts.")
    parser.add_argument("--feature", type=str, help="Feature or product to apply SCAMPER to")
    parser.add_argument("--input", type=str, help="Path to JSON with feature description")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    args = parser.parse_args()

    feature = args.feature
    if args.input:
        with open(args.input, "r") as f:
            data = json.load(f)
            feature = data.get("feature", feature)

    if not feature:
        parser.error("--feature or --input is required")

    result = generate_scamper(feature)
    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print_report(result)


if __name__ == "__main__":
    main()
